application: jaceyphotographs
version: 1
runtime: python
api_version: 1

handlers:
- url: /photos/(.*)/(.*\.(gif|png|jpg))
  static_files: static/photos/\1/\2
  upload: static/photos/(.*)/(.*\.(gif|png|jpg)) 
  
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /robots.txt
  static_files: static/files/robots.txt
  upload: static/files/robots.txt
  
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images
  
- url: /js
  static_dir: static/js
  
- url: /post/entry
  script: main.py
  login: admin
  
- url: /admin
  script: main.py
  login: admin

- url: /.*
  script: main.py
  
  